# action.yml
name: 'Texlive Build'
description: 'Build a document using texlive'
runs:
  using: 'docker'
  image: 'docker://DoeringChristian/mszep/pandoc_resume:master'
  entrypoint: '/entrypoint.sh'
